// Every user-facing string lives here (Turkish only).
export const tr = {
  app: "Yüzen Oda",
  tabs: { calendar: "Takvim", payments: "Ödemelerim", alerts: "Uyarılar", admin: "Yönetim" },
  theme: { toLight: "Açık temaya geç", toDark: "Koyu temaya geç" },
  loading: "Oda uyanıyor…",
  login: {
    title: "Yüzen Oda'ya hoş geldin",
    body: "Yeni misin? Hesap oluştur!\nYönetici onayladıktan sonra\nuygulamayı kullanabilirsin.\nBu cihaz seni uzun süre hatırlar.",
    invalid: "Bu davet bağlantısı geçersiz ya da yenilenmiş. Aşağıdan yeni bir hesap oluşturabilirsin.",
    lost: "Zaten üyeysen ve telefonunu değiştirdiysen yöneticiden yeni bir giriş bağlantısı iste.",
    email: "E-posta",
    password: "Şifre",
    submit: "Giriş yap",
    signupLink: "Hesabın yok mu? Hesap oluştur",
    forgot: "Şifremi unuttum",
  },
  signup: {
    open: "Hesap oluştur",
    title: "Hesap oluştur",
    name: "İsim",
    email: "E-posta",
    emailHint: "Giriş ve bildirimler için",
    phone: "Telefon",
    phoneHint: "İsteğe bağlı",
    password: "Şifre",
    passwordHint: "En az 8 karakter",
    submit: "Hesap oluştur",
    back: "Vazgeç",
    hint: "Hesabın oluşturulunca yönetici onayını beklersin.",
    loginLink: "Zaten hesabın var mı? Giriş yap",
  },
  pending: {
    title: "Onay bekleniyor",
    body: (name) => `${name}, hesabın oluşturuldu. Yönetici onayladığında oda rezervasyonu ve ödemeler açılacak. Bu sayfa kendiliğinden güncellenir.`,
    check: "Durumu kontrol et",
    stillWaiting: "Henüz onaylanmadı.",
  },
  profile: {
    open: "Profilim",
    title: "Profil",
    name: "İsim",
    phone: "Telefon",
    phoneHint: "İsteğe bağlı",
    role: "Rol",
    roleAdmin: "Yönetici",
    roleMember: "Üye",
    joined: "Katılım",
    months: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    save: "Kaydet",
    saved: "Profil güncellendi",
    logout: "Çıkış yap",
    loggingOut: "Çıkış yapılıyor…",
  },
  cal: {
    title: "Takvim",
    book: "Rezervasyon yap",
    observer: "Gözlemci yönetici hesabısın: takvimi görebilir, gerekirse rezervasyon iptal edebilirsin ama rezervasyon yapamazsın.",
    free: "Boş",
    pastSlot: "Geçti",
    freeHint: "Rezerve et",
    days: "Gün seç",
    weekPrev: "Önceki hafta",
    weekNext: "Sonraki hafta",
    dayPrev: "Önceki gün",
    dayNext: "Sonraki gün",
    viewLabel: "Görünüm",
    viewDay: "Gün",
    viewWeek: "Hafta",
    today: "Bugün",
    mine: "Senin",
    newTitle: "Yeni rezervasyon",
    start: "Başlangıç",
    duration: "Süre",
    hours: (n) => `${n} saat`,
    note: "Not (isteğe bağlı)",
    notePh: "Örn. grup provası",
    people: "Kişi sayısı",
    peopleHint: "Sen dahil kaç kişi geleceksin? Ücret kişi başıdır ve sana yansır.",
    peopleCount: (n) => `${n} kişi`,
    fewer: "Bir kişi azalt",
    more: "Bir kişi artır",
    submit: "Rezerve et",
    cancel: "Vazgeç",
    close: "Kapat",
    booked: "Rezervasyon alındı",
    booker: "Rezerve eden",
    cancelBooking: "Rezervasyonu iptal et",
    cancelSure: "Emin misin?",
    cancelYes: "Evet, iptal et",
    cancelled: "Rezervasyon iptal edildi",
    held: "Rezerve ediliyor",
    heldBy: (name) => `${name} seçiyor`,
    adminCancel: "Yönetici olarak iptal et…",
    dangerTitle: "Başkasının rezervasyonu",
    dangerBody: (name) => `Bu rezervasyon ${name} adlı üyeye ait. İptal edersen saat başkalarına açılır, üyenin ücreti iptal edilir ve nedenin yönetici kaydına işlenir. Bunu yalnızca gerçekten gerekiyorsa yap.`,
    dangerConfirm: (first) => `Onaylamak için üyenin adını yaz: ${first}`,
    dangerReason: "İptal nedeni (en az 5 karakter)",
    dangerReasonPh: "Örn. oda bakıma alınacak",
    dangerGo: "Üyenin rezervasyonunu iptal et",
    noFree: "Bu gün için boş saat kalmadı.",
    range: (a, b) => `${a} – ${b}`,
  },
  placeholder: {
    payments: ["Ödemelerim", "Aidat ve rezervasyon ücretlerin yakında burada olacak."],
    alerts: ["Uyarılar", "Oda uyarıları yakında burada olacak."],
  },
  members: {
    title: "Üyeler",
    add: "Üye ekle",
    name: "İsim",
    email: "E-posta (isteğe bağlı)",
    phone: "Telefon (isteğe bağlı)",
    role: "Rol",
    roleMember: "Üye",
    roleAdmin: "Yönetici",
    admin: "Yönetici",
    create: "Oluştur",
    cancel: "Vazgeç",
    pendingTitle: "Onay bekleyenler",
    pendingBadge: "Onay bekliyor",
    approve: "Onayla",
    reject: "Reddet",
    rejectConfirm: (n) => `${n} kaydı reddedilsin mi? Hesap silinir.`,
    approved: "Üye onaylandı",
    rejected: "Kayıt reddedildi",
    signedUp: "Kayıt",
    inactive: "Pasif",
    since: "Katılım",
    empty: "Henüz üye yok.",
    created: "Üye eklendi",
    roleChanged: "Rol güncellendi",
    you: "sen",
    pendingCount: (n) => `${n} onay bekleyen üye`,
  },
  alerts: {
    title: "Uyarılar",
    hint: "Bir şey bittiyse ya da bozulduysa dokun; herkes görür, biri halleder.",
    tap: "Bildirmek için dokun",
    bannerLabel: "Açık oda uyarıları",
    raised: "Bildirildi",
    already: (who) => `Zaten bildirilmiş (${who})`,
    ago: ({ n, unit }) => (unit === "now" ? "az önce" : `${n} ${{ min: "dk", hour: "sa", day: "gün" }[unit]} önce`),
    raisedAgo: (who, when) => `${who} ${when} bildirdi`,
    longOpen: "2 günden uzun süredir açık",
    // Accessible label for a topbar alert badge (icon-only until tapped, so a screen reader needs the full sentence).
    badgeLabel(problem, urgent, raisedAgo) { return `${problem} — ${urgent ? this.longOpen + " · " : ""}${raisedAgo}`; },
    history: "Geçmiş",
    noHistory: "Henüz uyarı yok.",
    by: (who, when) => `${who} bildirdi · ${when}`,
    doneBy: (who, when) => `${who} çözdü · ${when}`,
    stillOpen: "Hâlâ açık",
    more: "Daha fazla göster",
  },
  kinds: {
    title: "Uyarı türleri",
    add: "Tür ekle",
    edit: "Düzenle",
    editTitle: "Türü düzenle",
    icon: "Simge (emoji)",
    problem: "Sorun metni (örn. Galoş yok)",
    resolved: "Çözüm düğmesi (örn. Galoş aldım)",
    save: "Kaydet",
    delete: "Sil",
    saved: "Kaydedildi",
    deleted: "Silindi",
    up: "Yukarı taşı",
    down: "Aşağı taşı",
  },
  billing: {
    title: "Ödemelerim",
    monthPrev: "Önceki ay",
    monthNext: "Sonraki ay",
    kalan: "Kalan ödenecek",
    total: "Toplam",
    allPaid: "Bu ay için ödenecek bir şey yok",
    payTo: "Havale bilgileri",
    holder: "Hesap sahibi",
    iban: "IBAN",
    copyIban: "IBAN'ı kopyala",
    copied: "IBAN kopyalandı",
    noIban: "Yönetici henüz IBAN girmedi.",
    items: "Kalemler",
    noItems: "Bu ay için kalem yok.",
    subscription: "Aylık aidat",
    booking: "Rezervasyon",
    adjustment: "Düzeltme",
    cancelledRes: "iptal edildi",
    status: { paid: "Ödendi", unpaid: "Ödenmedi", partial: "Kısmen ödendi", waived: "Muaf", voided: "İptal", mismatch: "Tutar uyuşmadı", unreadable: "İnceleniyor", duplicate: "Tekrar dekont", pending: "Onay bekliyor", upcoming: "Planlanan" },
    future: {
      badge: "Gelecek ay",
      planned: "Planlanan aidat",
      hint: "Bu ay henüz başlamadı. Aidat ay başında kesinleşir; o zamana kadar tutar değişebilir.",
      empty: ["Bu ay için henüz bir şey yok", "Rezervasyon yaptıkça burada görünür."],
    },
    cover: {
      title: "Alacağın bu ayı karşılıyor",
      titlePart: "Alacağın bu ayın bir kısmını karşılıyor",
      full: (amt) => `Bu ayın ${amt} tutarındaki ödemesi mevcut alacağından karşılanabilir - örneğin kira önceki aydan fazla ödediğin tutarla zaten ödenmiş sayılabilir.`,
      part: (cov, need) => `Mevcut alacağın bu ayın ${need} tutarının ${cov} kısmını karşılayabilir.`,
      prior: (amt) => `Önceki aylara ayrılan ${amt} düşüldükten sonra.`,
      manual: "Yönetici alacağı bu aya mahsup edince kalemler ödendi olarak görünür.",
    },
    remaining: "Kalan",
    ofAmount: (paid) => `${paid} ödendi`,
    paidBy: { auto: "dekont doğrulandı", admin: "yönetici kaydetti" },
    howTitle: "Ödeme nasıl yapılır?",
    howNote: "Yukarıdaki IBAN'a havale/EFT yap. Dekontunu elden yöneticine iletebilir ya da aşağıdan yükleyebilirsin - iki yolda da ödemeyi yönetici inceleyip kaydeder, hiçbir şey otomatik olmaz.",
    credit: {
      title: "Alacağın",
      owed: (amt) => `Topluluk sana ${amt} borçlu`,
      owedAdmin: (amt) => `Topluluk üyeye ${amt} borçlu`,
      hint: "Fazla ödemenden kalan tutar. Yönetici iade edince ya da kapatınca burada görünmez.",
      settled: "Kapatılanlar",
      none: "Alacak yok",
    },
    onlyPdf: "Lütfen dekontu PDF olarak seç.",
    uploadPick: "Dekont yükle",
    uploading: "Yükleniyor…",
    uploaded: "Dekont yüklendi, yönetici onayını bekliyor.",
    receipts: "Kayıtlı ödemeler",
    view: "Dekontu aç",
    coversSelf: "Kapsadığı kalemler",
    owedSelf: "Topluluk sana borçlu",
  },
  admin: {
    sections: { members: "Üyeler", receipts: "Ödemeler", fees: "Ücretler", economics: "Ekonomi", settings: "Ayarlar" },
    all: "Tümü",
    allMonths: "Tüm ayların dekontlarını göster",
    month: "Ay",
    member: "Üye",
    receiptsTitle: "Dekontlar",
    overview: {
      title: "Ödemeler",
      member: "Üye",
      thisMonth: "Bu ay kalan",
      debt: "Toplam borç",
      totalOutstanding: "Seçili ayda toplam kalan",
      totalDebt: "Tüm zamanların toplam borcu",
      totalRow: "Toplam",
      owing: (n, all) => `${all} üyeden ${n} tanesinin borcu var`,
      allClear: "Kimsenin ödenmemiş borcu yok",
      inactive: "pasif",
      open: (name) => `${name} adlı üyenin ödemelerini aç`,
      empty: ["Üye yok", "Üye ekleyince borç durumu burada görünür."],
    },
    statusLabel: "Durum",
    empty: "Kayıt yok.",
    expected: "Beklenen",
    approve: "Ödemeyi onayla",
    reject: "Dekontu reddet",
    reviewHint: "Onayla: ödeme üyenin bakiyesine işlenir ve kalemler ödendi sayılır. Reddet: bu dekont sayılmaz, üyeye nedeni gösterilir.",
    pendingHint: "Üye bu dekontu yükledi, henüz incelenmedi. Neyi kapsadığını seç, ödenen tutarı gir, sonra onayla ya da reddet.",
    approved: "Onaylandı",
    rejected: "Reddedildi",
    notePh: "Not (isteğe bağlı)",
    covers: "Kapsadığı kalemler",
    applied: "Sayılan",
    remainingLeft: "Kalan",
    overpaid: "Fazla (alacak)",
    credit: {
      title: "Alacak (topluluk üyeye borçlu)",
      amountLabel: "Kapatılacak tutar (boş = tamamı)",
      notePh: "Not: örn. IBAN'a iade edildi",
      settle: "Alacağı kapat / iade edildi",
      settled: "Alacak kapatıldı",
      history: "Kapatma geçmişi",
    },
    bankRef: "İşlem no",
    noPdf: "PDF yok",
    openPdf: "PDF'i yeni sekmede aç",
    detail: "Ödemeler",
    back: "Üyelere dön",
    payments: "Dekontlar",
    reservations: "Rezervasyonlar",
    noReservations: "Rezervasyon yok.",
    resTotal: "Rezervasyon toplamı",
    cancelledRes: "iptal",
    waive: "Muaf tut",
    unwaive: "Muafiyeti kaldır",
    waived: "Muaf tutuldu",
    pay: {
      title: "Ödeme kaydet",
      hint: "Bu ödemenin hangi kalemleri kapsadığını seç, ödenen tutarı yaz, varsa dekontu PDF olarak ekle. Onaylayınca ödeme kaydedilir.",
      covers: "Bu ödeme neyi kapsıyor?",
      coversSaved: "Kapsadığı kalemler",
      pickFirst: "Önce bu ödemenin kapsadığı kalemleri seç.",
      itemLeft: (amt) => `kalan ${amt}`,
      selectedSum: (n) => `Seçilen ${n} kalemin toplamı`,
      amount: "Ödenen tutar (TL)",
      paid: "Ödenen tutar",
      left: "Kalan borç",
      exact: "Tam ödendi",
      spill: "Artan, ayın diğer kalemlerine",
      spillSaved: "Artan, ayın diğer kalemlerine sayıldı",
      owed: "Topluluk üyeye borçlu",
      pickPdf: "Dekont PDF'i yükle",
      changePdf: "Başka PDF seç",
      clearPdf: "Kaldır",
      showPdf: "PDF'i göster",
      hidePdf: "PDF'i gizle",
      dupWarn: "Bu dekont daha önce kaydedilmiş görünüyor. Yine de kaydedildi.",
      note: "Not (örn. nakit, elden ödendi)",
      submit: "Ödemeyi onayla",
      saved: "Ödeme kaydedildi",
      draft: "Kaydedilmedi",
      savedPill: "Kaydedildi",
      none: "Bu ay ödenmemiş kalem yok.",
      otherMonths: "Diğer aylar (eski borç, gelecek ay)",
      fromCredit: (amt) => `Alacaktan öde (mevcut alacak ${amt})`,
      fromCreditHint: "Yeni para yok: seçilen kalemler üyenin mevcut alacağından ödenir, alacak o kadar azalır. Dekont eklenmez.",
      creditUsed: "Alacaktan mahsup",
      overCredit: "Tutar mevcut alacaktan fazla olamaz.",
      undo: "Bu kaydı geri al",
      undoHint: "Geri alınan ödeme hiçbir bakiyeye sayılmaz, kalemler yeniden ödenmemiş olur.",
      undoBtn: "Ödemeyi geri al",
      redo: "Yeniden onayla",
    },
    adjust: "Ek ücret ekle",
    adjustAmount: "Tutar (TL)",
    adjustLabel: "Açıklama",
    adjustPh: "Örn. anahtar kopyası",
    adjustAdd: "Ekle",
    adjusted: "Ek ücret eklendi",
    feesTitle: "Ücretler",
    feesNow: "Şu an geçerli",
    feesSub: "Aylık aidat",
    feesBook: "Rezervasyon (kişi başı)",
    feesFrom: "Geçerli olduğu ay",
    feesNew: "Yeni ücret",
    feesNote: "Yeni ücret yalnızca seçilen aydan itibaren oluşan kalemleri etkiler; mevcut kalemler eski tutarıyla kalır.",
    feesSave: "Kaydet",
    feesSaved: "Ücret kaydedildi",
    feesHistory: "Geçmiş",
    settingsTitle: "Ödeme ayarları",
    settingsIban: "IBAN",
    settingsHolder: "Hesap sahibi adı",
    settingsRequire: "Dekont okunurken alıcı IBAN ya da ismi de aranır",
    settingsRequireHint: "Açıkken, dekont önizlemesinde yukarıdaki IBAN ya da isim bulunamazsa uyarı verilir. Ödemeyi yine de sen kaydedersin.",
    settingsSave: "Kaydet",
    settingsSaved: "Ayarlar kaydedildi",
  },
  eco: {
    title: "Ekonomi",
    chartTitle: "Gelir ve gider, son 6 ay",
    chartDesc: (rows) => `Aylık tahsil edilen gelir, beklenen gelir ve gider. ${rows}`,
    rowDesc: (m, e, c, g) => `${m}: beklenen ${e}, tahsil edilen ${c}, gider ${g}.`,
    income: "Tahsil edilen",
    expected: "Beklenen",
    cost: "Gider",
    balance: "Bakiye",
    table: "Tablo olarak göster",
    chart: "Grafik olarak göster",
    thMonth: "Ay",
    monthCosts: "Aylık giderler",
    total: "Toplam",
    empty: "Bu ay için gider yok.",
    category: "Kategori",
    amount: "Tutar (TL)",
    note: "Not (isteğe bağlı)",
    add: "Gider ekle",
    added: "Gider eklendi",
    save: "Kaydet",
    saved: "Kaydedildi",
    remove: "Sil",
    edit: "Düzenle",
    cancel: "Vazgeç",
    custom: "Başka…",
    customPh: "Kategori adı",
    templates: "Şablonlar",
    templatesHint: "Şablondaki giderler, bir ay ilk açıldığında otomatik eklenir. Sonradan silmek şablonu etkilemez.",
    tplAdd: "Şablona ekle",
    tplNone: "Şablon yok.",
    tplSaved: "Şablon kaydedildi",
    tplRemoved: "Şablon silindi",
    sugTitle: "Fiyat önerisi",
    sugCovered: "Gelir gideri karşılıyor. Fiyat artışı gerekmiyor.",
    sugNoCosts: "Öneri için gider girin.",
    sugNoBase: "Öneri için üye veya rezervasyon verisi yok.",
    sugRaise: (s, b) => `Maliyet arttı → önerilen abonelik ${s}, rezervasyon ${b}`,
    sugAlt: "Alternatifler",
    altSub: (s) => `Yalnızca abonelik: ${s}`,
    altBook: (b) => `Yalnızca rezervasyon: ${b}`,
    apply: "Uygula (gelecek aydan)",
    applyAlt: "Uygula",
    applied: (m) => `${m} ayından itibaren geçerli`,
    now: "Şu an",
    avg: (c, n, p, buf) => `Son 3 ay ortalaması: gider ${c}, ${n} üye, ${p} rezervasyon kalemi/ay, %${buf} pay.`,
    caveat: "Rezervasyon geliri kullanıma bağlıdır; bu bir tahmindir (son 3 ayın ortalaması). Yeni ücret yalnızca gelecek ayın kalemlerini etkiler.",
    unavailable: "Yeterli veri yok",
  },
  bootSlow: "Sunucu uyanıyor, ilk açılış bir dakikaya kadar sürebilir.",
  err: {
    generic: "Bir şeyler ters gitti. Tekrar dene.",
    loadTitle: "Yüklenemedi",
    load: "Sunucuya ulaşılamadı. Bağlantını kontrol edip tekrar dene.",
    retry: "Tekrar dene",
    boot: "Sunucuya ulaşılamadı. Uyanması biraz sürebilir; birazdan tekrar dene.",
  },
  empty: {
    members: ["Henüz üye yok", "Yeni üyeler giriş ekranından hesap oluşturur; onay bekleyenler burada görünür."],
    receipts: ["Kayıtlı ödeme yok", "Seçili filtrelere uyan ödeme kaydı bulunmuyor."],
    history: ["Henüz uyarı yok", "Bir şey bittiğinde ya da bozulduğunda yukarıdan bildirebilirsin."],
    kinds: ["Uyarı türü yok", "Yukarıdan ilk türü ekle."],
    items: ["Bu ay için kalem yok", "Aidat ve rezervasyon ücretleri burada listelenir."],
    reservations: ["Rezervasyon yok", "Bu üyenin kayıtlı rezervasyonu bulunmuyor."],
    alertsNoKinds: ["Uyarı türü tanımlı değil", "Yönetici Yönetim sekmesinden uyarı türü ekleyebilir."],
  },
  export: {
    title: "Yedek / dışa aktar",
    hint: "Ücretsiz veritabanının yedeği bu dosyadır. Ayda bir indirip sakla; üyeler, ücretler, rezervasyonlar, kalemler, dekont bilgileri, giderler ve ayarlar içerir. Giriş bağlantıları (gizli anahtarlar) dosyaya konmaz.",
    json: "Dışa aktar (JSON)",
    csv: "Kalemler (CSV)",
    withPdf: "Dekont PDF'lerini de ekle (büyük dosya)",
  },
};
